-- Ask Grid conversation storage.
-- Run this once in your Supabase SQL editor.

create table if not exists public.ask_conversations (
  id text primary key,
  privy_user_id text not null references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.ask_messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null references public.ask_conversations(id) on delete cascade,
  role text not null check (role in ('user', 'grid')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists ask_messages_conversation_id_idx
  on public.ask_messages (conversation_id);

alter table public.ask_conversations enable row level security;
alter table public.ask_messages enable row level security;

create policy "Users manage own conversations"
  on public.ask_conversations
  for all
  using (auth.uid() = privy_user_id)
  with check (auth.uid() = privy_user_id);

create policy "Users manage own messages"
  on public.ask_messages
  for all
  using (
    exists (
      select 1 from public.ask_conversations
      where id = conversation_id and privy_user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.ask_conversations
      where id = conversation_id and privy_user_id = auth.uid()
    )
  );
